name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4'
        bundler-cache: true
    
    - name: Install dependencies
      run: |
        gem install minitest
        npm install
    
    - name: Install Playwright browsers
      run: |
        npx playwright install chromium
        npx playwright install-deps
    
    - name: Run Ruby-first test workflow
      run: |
        ./bin/test
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-ruby-3.4
        path: |
          test/test_results_comprehensive.json
          test/screenshots/
          test-results/